name: fastapi-app

services:
  db:
    image: postgis/postgis:17-3.4
    container_name: db
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql@17/data
      - ./app/db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: ./app
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${SQL_USER}:${SQL_PASSWORD}@db:5432/${SQL_DATABASE}
    env_file:
      - .env

volumes:
  postgres-data:
